version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  backend:
    build: ./api
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./api:/app
      - /app/node_modules
    depends_on:
      - mongodb

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true

    depends_on:
      - backend

volumes:
  data:
  logs:
  